### PR TITLE
Update class-utility.php

### PR DESCRIPTION
**Pull request by ghost**
just return null if the $key is a falsy string in the generate_jwt_token function

### CODE REVIEW

**Comment by ghost** [comment]
https://github.com/udx/wp-stateless/issues/650 

issue link

**Comment by KalleVuorjoki** [comment]
+1 for adding this

**Comment by ghost** [comment]
@KalleVuorjoki  

They need to deal with the issue as my pull request didn't solve it completely. After returning null, I faced other issues related to this. 

I ended up using another plugin for this use case

**Comment by KalleVuorjoki** [comment]
@mjad218 do you remember more specific what where the other issues? And what plugin did you choose instead?

**Comment by ghost** [comment]
That was a long time ago. But I think it was that other places depend on the key and can't accept null as a value. 

I thought of returning an empty string but I didn't try it.

**Comment by KalleVuorjoki** [comment]
Thanks for the reply. Reading the change more carefully I'll take my words back. This plugin should check existence of  `AUTH_SALT` earlier, so it wouldn't give fatal error on `wpCloud\StatelessMedia\Utility::generate_jwt_token()` if the variable is missing.

**Comment by planv** [comment]
Will be solved in version `3.2.3`

**Pull request closed without merging**
