### PR TITLE
#560 elementor compatibility

### PR DESCRIPTION
**Pull request by alimuzzaman**

### CODE REVIEW

**Comment by antonkorotkov** [comment]
@alimuzzaman Another issue found here. In `Backup` mode Elementor should upload files to GCS (as it does) but local files should be served instead. Right now it always tries to get the file from remote unless the mode is `Disabled`.

**Review by antonkorotkov — CHANGES_REQUESTED** [review]
Another bug should be addressed https://github.com/udx/wp-stateless/pull/562#issuecomment-701194060

**Comment by antonkorotkov** [comment]
@alimuzzaman also, do we have an option to clean up the `sm_sync` table somehow? In my example, I have some orphaned data related to the files that do not exist any more. And they are being tried to sync every time I run manual sync. Only `elementor/css/*` files really exist after your fix but the old ones are still there. Do you think we can add a button of sorts to clear this table? Or it cannot be cleared? 

image

**Comment by alimuzzaman** [comment]
@antonkorotkov
If both file missing when doing manual sync we can remove the entry from the table.

Yes, we can add a button to clear the table. There shouldn't be any problem doing it. But should test in Stateless mode.

**Comment by antonkorotkov** [comment]
> @antonkorotkov
> If both file missing when doing manual sync we can remove the entry from the table.

Can you please implement this? If we do this we don't need a button.

**Review by antonkorotkov — APPROVED** [review]
It works, thanks.

**Pull request merged**
