### PR TITLE
wpCloud#343 Account for dirname() '.' on filename with no path

### PR DESCRIPTION
**Pull request by jjtroberts**

### CODE REVIEW

**Comment by jjtroberts** [comment]
See https://github.com/wpCloud/wp-stateless/issues/343

TL;DR

The Wordpress option to stop storing files in year/month directories results in assets in uploads and then dirname() returns a . when there are no slashes:

> Returns the path of a parent directory. If there are no slashes in path, a dot ('.') is returned, indicating the current directory. Otherwise, the returned string is path with any trailing /component removed.
> ref: http://php.net/manual/en/function.dirname.php

**Comment by antonkorotkov** [comment]
@gd-jroberts Hey. Just to clarify, the main issue you described in #343 is fixed by this PR?

**Comment by jjtroberts** [comment]
Yes, it resolves the issue I was having with any version greater than 2.1.5.

**Comment by antonkorotkov** [comment]
@gd-jroberts thanks for sharing. I was able to replicate the issue and included your fix to the next release. But I'll have to close the PR because it is done in the wrong branch that breaks our release workflow. Corresponding commit https://github.com/wpCloud/wp-stateless/commit/91a8c89becfde73ca0868d6314220591dab0f971

**Comment by jjtroberts** [comment]
Understandable. Thank you.

**Pull request closed without merging**
